apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-sample
    app.kubernetes.io/part-of: test-app-165787017
  name: nodejs-sample
  namespace: sbudhwar-1
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-sample
status:
  loadBalancer: {}
